const PrivacyPolicy = () => {
  return (
    <div className="p-4 md:p-5 space-y-4">
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400 text-[20px]">
        Privacy Policy
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400">
        {`ThaiScamLinks ("we," "our," or "us") is committed to
                      protecting your privacy. This Privacy Policy explains how
                      your personal information is collected, used, and
                      disclosed by ThaiScamLinks. This Privacy Policy applies to
                      our website, www.ThaiScamLinks.com, and its associated
                      subdomains (collectively, our "Service"). By accessing or
                      using our Service, you signify that you have read,
                      understood, and agree to our collection, storage, use, and
                      disclosure of your personal information as described in
                      this Privacy Policy and our Terms of Service.`}
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400 text-[20px]">
        Definitions and key terms
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400">
        To help explain things as clearly as possible in this Privacy Policy,
        every time any of these terms are referenced, are strictly defined as:
      </p>
      <p className="indent-5 list-disc text-base leading-relaxed text-gray-500 dark:text-gray-400">
        <li>
          Cookie: a small amount of data generated by a website and saved by
          your web browser. It is used to identify your browser, provide
          analytics, and remember information about you such as your language
          preference or login information.
        </li>
        <li>
          Company: When this policy mentions “Company,” “we,” “us,” or “our,” it
          refers to ThaiScamLinks which is responsible for your information
          under this Privacy Policy.
        </li>
        <li>
          Country: where ThaiScamLinks or the owners/founders of ThaiScamLinks
          are based, in this case, Thailand.
        </li>
        <li>
          Customer: refers to the company, organization, or person that signs up
          to use the ThaiScamLinks Service to manage the relationships with your
          consumers or service users.
        </li>
        <li>
          Device: any internet-connected device such as a phone, tablet,
          computer, or any other device that can be used to visit ThaiScamLinks
          and use the services.
        </li>
        <li>
          IP address: Every device connected to the Internet is assigned a
          number known as an Internet protocol (IP) address. These numbers are
          usually assigned in geographic blocks. An IP address can often be used
          to identify the location from which a device is connecting to the
          Internet.
        </li>
        <li>
          Personnel: refers to those individuals who are employed by
          ThaiScamLinks or are under contract to perform a service on behalf of
          one of the parties.
        </li>
        <li>
          Personal Data: any information that directly, indirectly, or in
          connection with other information — including a personal
          identification number — allows for the identification or
          identifiability of a natural person.
        </li>
        <li>
          Service: refers to the service provided by ThaiScamLinks as described
          in the relative terms (if available) and on this platform.
        </li>
        <li>
          Third-party service: refers to advertisers, contest sponsors,
          promotional and marketing partners, and others who provide our content
          or whose products or services we think may interest you.
        </li>
        <li>
          Website: ThaiScamLinks’s site, which can be accessed via this URL:
          www.ThaiScamLinks.com.
        </li>
        <li>
          You: a person or entity that is registered with ThaiScamLinks to use
          the Services.
        </li>
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400 text-[20px]">
        What Information Do We Collect?
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400">
        We collect information from you when you visit our service, register,
        place an order, subscribe to our newsletter, respond to a survey, or
        fill out a form.
      </p>
      <p className="indent-5 text-base leading-relaxed text-gray-500 dark:text-gray-400">
        <li>Name / Username</li>
        <li>Phone Numbers</li>
        <li>Email Addresses</li>
        <li>Password</li>
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400 text-[20px]">
        How Do We Use The Information We Collect?
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400">
        Any of the information we collect from you may be used in one of the
        following ways:
      </p>
      <p className="indent-5 text-base leading-relaxed text-gray-500 dark:text-gray-400">
        <li>
          To personalize your experience (your information helps us to better
          respond to your individual needs)
        </li>
        <li>
          To improve our service (we continually strive to improve our service
          offerings based on the information and feedback we receive from you)
        </li>
        <li>
          To improve customer service (your information helps us to more
          effectively respond to your customer service requests and support
          needs)
        </li>
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400 text-[20px]">
        Could my information be transferred to other countries?
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400">
        We are incorporated in Thailand. Information collected via our website,
        through direct interactions with you, or from the use of our help
        services may be transferred from time to time to our offices or
        personnel, or to third parties, located throughout the world, and may be
        viewed and hosted anywhere in the world, including countries that may
        not have laws of general applicability regulating the use and transfer
        of such data. To the fullest extent allowed by applicable law, by using
        any of the above, you voluntarily consent to the trans-border transfer
        and hosting of such information.
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400 text-[20px]">
        Is the information collected through our service secure?
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400">
        We take precautions to protect the security of your information. We have
        physical, electronic, and managerial procedures to help safeguard,
        prevent unauthorized access, maintain data security, and correctly use
        your information. However, neither people nor security systems are
        foolproof, including encryption systems. In addition, people can commit
        intentional crimes, make mistakes, or fail to follow policies.
        Therefore, while we use reasonable efforts to protect your personal
        information, we cannot guarantee its absolute security. If applicable
        law imposes any non-disclaimable duty to protect your personal
        information, you agree that intentional misconduct will be the standard
        used to measure our compliance with that duty.
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400 text-[20px]">
        Can I update or correct my information?
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400">
        Of course! You can be able to update your data via the profile page.
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400 text-[20px]">
        How Long Do We Keep Your Information?
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400">
        {`We keep your information only so long as we need it to
                      provide service to you and fulfill the purposes described
                      in this policy. This is also the case for anyone that we
                      share your information with and who carries out services
                      on our behalf. When we no longer need to use your
                      information and there is no need for us to keep it to
                      comply with our legal or regulatory obligations, we'll
                      either remove it from our systems or depersonalize it so
                      that we can't identify you.`}
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400 text-[20px]">
        Governing Law
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400">
        The laws of Thailand, excluding its conflicts of law rules, shall govern
        this Agreement and your use of our service. Your use of our service may
        also be subject to other local, state, national, or international laws.
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400 text-[20px]">
        Your Consent
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400">
        By using our service, registering an account, you consent to this
        Privacy Policy.
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400 text-[20px]">
        Cookies
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400">
        {`We use "Cookies" to identify the areas of our website that
                      you have visited. A Cookie is a small piece of data stored
                      on your computer or mobile device by your web browser. We
                      use Cookies to personalize the Content that you see on our
                      website. Most web browsers can be set to disable the use
                      of Cookies. However, if you disable Cookies, you may not
                      be able to access functionality on our website correctly
                      or at all. We never place Personally Identifiable
                      Information in Cookies.`}
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400 text-[20px]">
        Kids’ Privacy
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400">
        We do not address anyone under the age of 13. We do not knowingly
        collect personally identifiable information from anyone under the age of
        13. If You are a parent or guardian and You are aware that Your child
        has provided Us with Personal Data, please contact us. If We become
        aware that We have collected Personal Data from anyone under the age of
        13 without verification of parental consent, We take steps to remove
        that information from our servers.
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400 text-[20px]">
        Changes To Our Privacy Policy
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400">
        If we decide to change our privacy policy, we will post those changes on
        this page, and/or update the Privacy Policy modification date below.
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400 text-[20px]">
        Tracking Technologies
      </p>
      <p className="indent-5 text-base leading-relaxed text-gray-500 dark:text-gray-400">
        <li>Cookies</li>
        We use Cookies to enhance the performance and functionality of our
        service but are non-essential to their use. However, without these
        cookies, certain functionality like videos may become unavailable or you
        would be required to enter your login details every time you visit our
        service as we would not be able to remember that you had logged in
        previously.
        <li>Local Storage</li>
        Local Storage sometimes known as DOM storage, provides web apps with
        methods and protocols for storing client-side data. Web storage supports
        persistent data storage, similar to cookies but with a greatly enhanced
        capacity and no information stored in the HTTP request header.
        <li>Sessions</li>
        {`uses "Sessions" to identify the areas of our website that
                      you have visited. A Session is a small piece of data
                      stored on your computer or mobile device by your web
                      browser.`}
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400 text-[20px]">
        Information about the Personal Data Protection Act (PDPA) of Thailand
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400">
        We may be collecting and using information from you if you are in
        Thailand, and in this section of our Privacy Policy, we are going to
        explain exactly how and why this data is collected, and how we maintain
        this data under protection from being replicated or used in the wrong
        way.
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400 text-[20px]">
        What is PDPA?
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400">
        {`PDPA is a comprehensive privacy and data protection law in
                      Thailand that regulates how individuals' data is protected
                      by companies and enhances the control that individuals
                      have over their personal data.`}
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400 text-[20px]">
        What is personal data?
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400">
        Personal data, as defined by PDPA, refers to any information relating to
        an identifiable individual. PDPA covers a broad spectrum of information
        that could be used, either alone or in combination with other pieces of
        information, to identify a person. Examples include but are not limited
        to, name, contact details, financial information, biometric data, IP
        addresses, and more.
        <br></br>
        <br></br>
        The Data Protection Principles outlined in PDPA include requirements
        such as:
      </p>
      <p className="indent-5 text-base leading-relaxed text-gray-500 dark:text-gray-400">
        <li>
          Personal data collected must be processed in a fair, legal, and
          transparent way and should only be used in a way that a person would
          reasonably expect.
        </li>
        <li>
          Personal data should only be collected to fulfill a specific purpose,
          and it should only be used for that purpose. Organizations must
          specify why they need the personal data when they collect it.
        </li>
        <li>
          Personal data should be held no longer than necessary to fulfill its
          purpose.
        </li>
        Individuals covered by PDPA have the right to access their own personal
        data. They can also request a copy of their data, and that their data be
        updated, deleted, restricted, or transferred to another organization.
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400 text-[20px]">
        Why is PDPA important?
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400">
        {`PDPA introduces new requirements regarding how companies
                      should protect individuals’ personal data that they
                      collect and process. It emphasizes compliance through
                      increased enforcement and imposes penalties for breaches.
                      Beyond these legal requirements, we believe that
                      respecting your data privacy is crucial. At [Your Company
                      Name], we have robust security and privacy practices in
                      place that go beyond the PDPA regulations.`}
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400 text-[20px]">
        {`Individual Data Subject's Rights - Data Access, Portability, and Deletion`}
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400">
        We are committed to helping our customers meet the data subject rights
        requirements of PDPA. ThaiScamLinks.com processes or stores all personal
        data in fully vetted, PDPA-compliant vendors. We retain all conversation
        and personal data for up to 2024, unless your account is deleted. In
        such cases, we dispose of all data in accordance with our Terms of
        Service and Privacy Policy, but we will not hold it for longer than
        2025.
        <br></br>
        <br></br>
        {`We acknowledge the importance of providing individuals
                      with the ability to access, update, retrieve, and remove
                      personal data. We have designed our systems to be
                      self-service from the start, ensuring that you have access
                      to your data and your customer's data. Our customer
                      support team is here to assist you with any questions you
                      may have about working with the PDPA.`}
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400 text-[20px]">
        Contact Us
      </p>
      <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400">
        {`Don't hesitate to contact us if you have any questions.`}
        <li>Via Email: capcap241023@gmail.com</li>
      </p>
    </div>
  );
};

export default PrivacyPolicy;
