export default {

  "navbar": {
    "reportweb": "Report Websites",
    "verifyweb": "Check Website's Link",
    "signin": "Sign In",
    "signup": "Sign Up",
    "signout": "Sign Out",
    "TH": "Thai",
    "EN": "English"
  },

  "signinpage": {
    "signin": "Sign In",
    "signup": "Sign Up",
    "username": "Username",
    "text1": "Enter your username",
    "text2": "Enter your password",
    "password": "Password",
    "signupmes": "If you don't have a user account, click"
  },

  "signuppage": {
    "title": "Create Account",
    "signup": "Sign Up",
    "signin": "Sign In",
    "have": "Already have an account?",
    "username": "Username",
    "usertext": "Enter your username",
    "email": "Email",
    "emtext": "Enter your Email (example@gmail.com)",
    "phonenum": "Phone number (Optional)",
    "phntext": "Enter your phone number",
    "password": "Password",
    "pwtext": "Enter your password",
    "confirm": "Confirm Password",
    "cftext": "Enter your confirm password",
    "consent1": "Please read the",
    "termofuse": "Terms of Use",
    "and": "and",
    "privacypolicy": "Privacy Policy",
    "consent2": "to allow us to collect your data.",
    "errconfirmpass": "Password and confirm password should be the same.",
    "successmsg": "Information Validation Success.",
    "erremail": "Please enter a correct Email Format.",
    "errpw1": "Password must be at least 8 characters.",
    "errpw2": "Password must contain at least one number.",
    "errphone": "Please enter a correct phone number format.",
    "errconsent": "Please read and consent to the terms.",
    "warntext": "*Note* The username will be used to sign in and display when reports",
    "errfield": "Please fill out this field",
    "AItxt1": "(Optional) AI button to generate username",
    "AItxt2": "Generater",
  },


  "termofusepage": {
    "title": "Term of use",
    "accept": "I accept",
    // General Terms
    "generaltermtitle": "General Terms",
    "generaltermtxt1":
      ` By accessing Thai.CheckLinks, you confirm that
    you are in agreement with and bound by the terms of use contained
    in the Terms & Conditions outlined below. These terms apply to the
    entire website and any communication between you and Thai.CheckLinks.`,

    "generaltermtxt2": ` Under no circumstances shall the Thai.CheckLinks team be liable for any
    direct, indirect, special, incidental, or consequential damages,
    including, but not limited to, loss of data or profit, arising out of
    the use, or the inability to use, the materials on this site, even if
    Thai.CheckLinks team or an authorized representative has been advised of
    the possibility of such damages. If your use of materials from this
    site results in the need for servicing, repair, or correction of
    equipment or data, you assume any costs thereof.`,

    "generaltermtxt3": ` Thai.CheckLinks will not be responsible for any outcome that may occur
    during the usage of our resources. We reserve the right to change
    prices and revise the resource usage policy at any moment.`,
    // License
    "license": "License",
    "licensetxt": `Thai.CheckLinks grants you a revocable, non-exclusive, non-transferable, 
    limited license to download, install, and use the website strictly in accordance with the 
    terms of this Agreement.These Terms & Conditions are a contract between you and ThaiScamLinks.`,
    // Definitions and key terms
    "definition": "Definitions and key terms",
    "deftxt1": "For this Terms & Conditions:",

    "deftxt2": `Cookie: a small amount of data generated by a website and saved by
    your web browser. It is used to identify your browser, provide
    analytics, and remember information about you such as your language
    preference or login information.`,

    "deftxt3": `Company: When this policy mentions “Company,” “we,” “us,” or “our,” it
    refers to Thai.CheckLinks which is responsible for your information
    under this Privacy Policy.`,

    "deftxt4": `Country: where ThaiScamLinks or the owners/founders of ThaiScamLinks
    are based, in this case, Thailand.`,

    "deftxt5": `Customer: refers to the company, organization, or person that signs up
    to use the Thai.CheckLinks Service to manage the relationships with your
    consumers or service users.`,

    "deftxt6": `Device: any internet-connected device such as a phone, tablet,
    computer, or any other device that can be used to visit Thai.CheckLinks
    and use the services.`,

    "deftxt7": `IP address: Every device connected to the Internet is assigned a
    number known as an Internet protocol (IP) address. These numbers are
    usually assigned in geographic blocks. An IP address can often be used
    to identify the location from which a device is connecting to the
    Internet.`,

    "deftxt8": `Personal Data: any information that directly, indirectly, or in
    connection with other information — including a personal
    identification number — allows for the identification or
    identifiability of a natural person.`,

    "deftxt9": `Service: refers to the service provided by Thai.CheckLinks as described
    in the relative terms (if available) and on this platform.`,

    "deftxt10": `Third-party service: refers to advertisers, contest sponsors,
    promotional and marketing partners, and others who provide our content
    or whose products or services we think may interest you.`,

    "deftxt11": `Website: Thai.CheckLinks’s site, which can be accessed via this URL:
    www.thaiscamlinks.com.`,

    "deftxt12": `You: a person or entity that is registered with Thai.CheckLinks to use
    the Services.`,
    // Restrictions
    "restrictions": "Restrictions",
    "restxt": "You agree not to, and you will not permit others to;"

  },

  "privacypolicypage": {
    "title": "Privacy Policy"
  },

  "homepage": {
    "title": "Start Checking Website Links For Your Safety",
    "caption": "Enter your link in the verification box to check your website and stage percentage of scammers against the criminal history database.",
    "text": "Search URL link or category",
    "verify": "Verify",
    "rank": "Ranking fraudulent links",
    "detail": "Details",
    "category": "Category",
    "reportnum": "Reports Number",
    "more": "More details",
    "searchbutt": "Search",
    "reportbutt": "Report",
    "filter": "Filter",
    "alldefault": "All Defaults",
    "date": "Date/Time",
    "old": "Oldest Date",
    "new": "Lastest Date",
    "report": "Report Number",
    "high": "Highest Report",
    "low": "Lowest Report",
    "gambling": "Gambling",
    "scam": "Scam",
    "fake": "Fake",
    "others": "Others",
    "seemore": "See More",
    "seeall": "See All",
    "seeless": "See Less",
    "placeholder": "Enter link eg. https://www.example.com ...",
    "sort": "Sorting Filter"
  },

  "detailpage": {
    "title": "Crime Wesite Details",
    "category": "Category",
    "gambling": "Gambling",
    "scam": "Scam",
    "fake": "Fake",
    "others": "Others",
    "gamblingr": "Gambling Report",
    "scamr": "Scam Report",
    "faker": "Fake Report",
    "othersr": "Others Report",
    "searchtext": "Search Word",
    "searchbutt": "Search",
    "detail": "Details",
    "bank": "Bank Account",
    "more": "See More",
    "seemore": "See More",
    "seeall": "See All",
    "seeless": "See Less",
    "user": "User"
  },

  "report": {
    "title": "Start reporting suspicious website links",
    "caption": "Sign in or sign up before reporting information to ensure accuracy.",
    "signin": "Sign In",
    "signup": "Sign Up",
    "caption2": "Reporting unlawful links here can help investigators find criminal websites",
    "placeholder": "Enter link eg. https://www.example.com ...",
    "searchbutt": "Confirm",
    "Category": "Categories of suspicious links*",
    "typefield": "Categories",
    "moredetails": "How does this website risk*",
    "details": "Details (At Least 50 characters)",
    "bankacc": "Bank Account (Optional)",
    "banktext": "Bank Account Holder Name (Select 1 account if there are many)",
    "bankfield1": "Bank Account",
    "banknum": "Bank Account Number",
    "reportbutt": "Report",
    "gambling": "Gambling",
    "scam": "Scam",
    "fake": "Fake",
    "others": "Others",
    "bank": "Bank",
    "scb": "Siam Commercial Bank",
    "kbtg": "Kasikorn Bank",
    "ktb": "Krungthai Bank",
    "ttb": "TMBThanachart Bank",
    "boa": "Bank of Ayudhya",
    "lhb": "Land and Houses Bank",
    "gsb": "Government Savings Bank",
    "bankothers": "Others",
    "urlError": "Please provide the URL",
    "urlError2": "Please provide the correct URL's format",
    "urlError3": "URL contains invalid characters",
    "webCatError": "Please select your website category",
    "moredetailError": "Please provide more details about this website",
    "moredetailError2": "Please provide the details over than 50 characters",
    "moredetailError3": "Please do not use the redundancy word over 3 times",
  },

  "reportsuccess": {
    "title": "Successfully reported suspicious website links",
    "sub-title": "Thank you for reporting suspicious links here.",
    "sub-title2": "We will continue to use criminal web investigations to help the public.",
    "successmess": "Successful report"
  },

  "profilepage": {
    "title": "My Profile",
    "username": "Username",
    "email": "Email",
    "phonenum": "Phone number (Optional)",
    "password": "Password",
  },

  "verificationpage": {
    "title": "Start Checking Website Links For Your Safety",
    "caption": "Enter your link in the verification box to check your website and stage percentage of scammers against the criminal history database.",
    "url-detection-title": "URL Detection",
    "No Result": "No Result",
    "report": "Report",

    "overall-title": "Overview Of The Risks Of Website",
    "overall-subtitle": "The Percentage Of Risk Of Being An suspicious Website Is Based On All Citeria",
    "risk-value": "Risk value",
    "sum-percentage": "Total percentage",
    "low-score": "Low Risk",
    "quite-low-score": "Quite Low Risk",
    "quite-high-score": "Quite High Risk",
    "high-score": "High Risk",
    'risk-measurement-citeria': "Risk Measurement Criteria",
    "found-thai-scam-link": "Found In History Website Reported in Thai.CheckLinks",
    "found-ai": "Discover In AI Audit Risk Percentage",
    "url-measure": "URL Risks Measured By URL Detection",
    "found-other-database": "Found On The Other Website Checker",
    "seemore": "See More",
    "click-here": "Click here for addtional reports",

    "analysis-title": "AI Analyzes Risk Percent",
    "analysis-subtitle": "Highest Percentage Ever Examined",
    "see-overview": "SEE THE OVERVIEW",
    'update': 'current update',
    'analysis-most': "Analyzed as a",

    "report-title": "Verify The Database",
    "report-subtitle": "Verify Against The User Reporting Database In Thai.ScamLinks",
    "report-title-result": "Verification Result",
    "risk-title-count": "Risk rate based on number of reports",

    "low-risk-count": "Low risk with 0-5 reports",
    "moderate-risk-count": "Moderate risk with 6-10 reports",
    "quite-high-risk-count": "Quite high risk with 11-15 reports",
    "serious-risk-count": "Serious risk with 16+ reports",

    "low-count": "Low Risk",
    "quite-low-count": "Quite Low Risk",
    "quite-high-count": "Quite High Risk",
    "high-count": "Serious Risk",

    "gambling-label": "Gambing",
    "scam-label": "Scam",
    "fake-label": "Fake",
    "other-label": "Other",
    "gambling": "gambling",
    "scam": "scam",
    "fake": "fake",
    "other": "other",

    'report-found': 'FOUND IN DATABASE',
    'report-not-found': 'NOT FOUND IN DATABASE',
    'report-not-found2': 'FOUND BEING TYPE OTHER IN THE DATABASE',

    'report-most': "Most reported as",
    'report-unit': "People",

    "report-label-bar-plot": "Number of each type of reporting",

    "measure-title": "Verify From URL Detection",
    "measure-subtitle": "Check For Risks From URL Information",
    "measure-risk-title": "Risk Score",

    "API-title": "Compare API With Other Cheat Checking Websites",
    "API-subtitle": "Check The Website Againt A Database Of Other Verified Websites",
    "API-website-col": "Cheating Web Checking Websites",
    "API-inspection-result-col": "Inspection Results",
    "FOUND": "FOUND",
    "NOT FOUND": "NOT FOUND",
  },

  "moredetailpage": {
    "title": "Read More Website Details Here",
    "risk-score": "Risk Score:",
    "measurement": "Trust Score Measurement Criteria",
    "websiteinsight-title": "Website Insights",
    "API-title": "Compare API With Other Cheat Checking Websites",
    "API-website-col": "Cheating Web Checking Websites",
    "API-inspection-result-col": "Inspection Results",
    "FOUND": "FOUND",
    "NOT FOUND": "NOT FOUND",
    "No Result": "No Result",
    'positive': 'Positive',
    'negative': 'Negative'
  },

  "errormessage": {
    "errmessuserexist": "User with this username already exists",
    "errmessemailexist": "User with this email already exists",
    "errmessphoneexist": "User with this phone number already exists",
    "errmesspassword": "You can not change your password with your old password",
    "editnoinfo": "Require information for an update",
    "editerrinfo": "Something Wrong with your information",
    "editsuccess": "User information was edited successfully",
    "usersuccess": "User information was created successfully",
    "errsigninusername": "The provided username does not exist. Please sign up if you don't have an account.",
    "errsigninpassword": "Invalid password",
    "errsigninsystem": "We're experiencing technical difficulties. Please try signing in again in a few minutes.",
    "signinsuccess": "Authentication successful",
    "reporterrwebsiteinact": "This website may be inactive already",
    "reportsuccess": "Report information was created successfully",
    "errurl1": "Can not verify this website but user still can report this website",
    "errurl2": "Please check the machine learning connection but the user still can report this website",
  }
}