export default {

  "navbar": {
    "reportweb": "Report Websites",
    "verifyweb": "Check Website's Link",
    "signin": "Sign In",
    "signup": "Sign Up",
    "signout": "Sign Out",
    "TH": "Thai",
    "EN": "English"
  },

  "signinpage": {
    "signin": "Sign In",
    "signup": "Sign Up",
    "username": "Username",
    "text1": "Enter your username",
    "text2": "Enter your password at least 8 character with number",
    "password": "Password",
    "signupmes": "If you don't have a user account, click"
  },

  "signuppage": {
    "title": "Create Account",
    "signup": "Sign Up",
    "signin": "Sign In",
    "have": "Already have an account?",
    "username": "Username",
    "usertext": "Enter your username",
    "email": "Email",
    "emtext": "Enter your Email (example@gmail.com)",
    "phonenum": "Phone number (Optional)",
    "phntext": "Enter your phone number Ex.(0897654321)",
    "password": "Password",
    "pwtext": "Enter your password at least 8 character with number",
    "confirm": "Confirm Password",
    "cftext": "Enter your confirm password",
    "consent1": "Please read the",
    "termofuse": "Terms of Use",
    "and": "and",
    "privacypolicy": "Privacy Policy",
    "consent2": "to allow us to collect your data.",
    "errconfirmpass": "Password and confirm password should be the same.",
    "successmsg": "Information Validation Success.",
    "erremail": "Please enter a correct Email Format.",
    "errpw1": "Password must be at least 8 characters.",
    "errpw2": "Password must contain at least one number.",
    "errphone": "Please enter a correct phone number format.",
    "errconsent": "Please read and consent to the terms.",
    "warntext": "*Note* The username will be used to sign in and display when reports",
    "errfield": "Please fill out this field",
    "AItxt1": "(Optional) AI button to generate username",
    "AItxt2": "Generater",
  },


  "termofusepage": {
    "title": "Term of use",
    "accept": "I accept",
    // General Terms
    "generaltermtitle": "General Terms",
    "generaltermtxt1":
      ` By accessing Thai.CheckLinks, you confirm that
    you are in agreement with and bound by the terms of use contained
    in the Terms & Conditions outlined below. These terms apply to the
    entire website and any communication between you and Thai.CheckLinks.`,

    "generaltermtxt2": ` Under no circumstances shall the Thai.CheckLinks team be liable for any
    direct, indirect, special, incidental, or consequential damages,
    including, but not limited to, loss of data or profit, arising out of
    the use, or the inability to use, the materials on this site, even if
    Thai.CheckLinks team or an authorized representative has been advised of
    the possibility of such damages. If your use of materials from this
    site results in the need for servicing, repair, or correction of
    equipment or data, you assume any costs thereof.`,

    "generaltermtxt3": ` Thai.CheckLinks will not be responsible for any outcome that may occur
    during the usage of our resources. We reserve the right to change
    prices and revise the resource usage policy at any moment.`,
    // License
    "license": "License",
    "licensetxt": `Thai.CheckLinks grants you a revocable, non-exclusive, non-transferable, 
    limited license to download, install, and use the website strictly in accordance with the 
    terms of this Agreement.These Terms & Conditions are a contract between you and Thai.CheckLinks.`,
    // Definitions and key terms
    "definition": "Definitions and key terms",
    "deftxt1": "For this Terms & Conditions:",
    "deftxt2": `Cookie: a small amount of data generated by a website and saved by
    your web browser. It is used to identify your browser, provide
    analytics, and remember information about you such as your language
    preference or login information.`,
    "deftxt3": `Company: When this policy mentions “Company,” “we,” “us,” or “our,” it
    refers to Thai.CheckLinks which is responsible for your information
    under this Privacy Policy.`,
    "deftxt4": `Country: where Thai.CheckLinks or the owners/founders of Thai.CheckLinks
    are based, in this case, Thailand.`,
    "deftxt5": `Customer: refers to the company, organization, or person that signs up
    to use the Thai.CheckLinks Service to manage the relationships with your
    consumers or service users.`,
    "deftxt6": `Device: any internet-connected device such as a phone, tablet,
    computer, or any other device that can be used to visit Thai.CheckLinks
    and use the services.`,
    "deftxt7": `IP address: Every device connected to the Internet is assigned a
    number known as an Internet protocol (IP) address. These numbers are
    usually assigned in geographic blocks. An IP address can often be used
    to identify the location from which a device is connecting to the
    Internet.`,
    "deftxt8": `Personal Data: any information that directly, indirectly, or in
    connection with other information — including a personal
    identification number — allows for the identification or
    identifiability of a natural person.`,
    "deftxt9": `Service: refers to the service provided by Thai.CheckLinks as described
    in the relative terms (if available) and on this platform.`,
    "deftxt10": `Third-party service: refers to advertisers, contest sponsors,
    promotional and marketing partners, and others who provide our content
    or whose products or services we think may interest you.`,
    "deftxt11": `Website: Thai.CheckLinks’s site, which can be accessed via this URL:
    www.thaiscamlinks.com.`,
    "deftxt12": `You: a person or entity that is registered with Thai.CheckLinks to use
    the Services.`,

    // Restrictions
    "restrictions": "Restrictions",
    "restxt1": "You agree not to, and you will not permit others to;",
    "restxt2": `License, sell, rent, lease, assign, distribute, transmit, host,
    outsource, disclose, or otherwise commercially exploit the service or
    make the platform available to any third party.`,
    "restxt3": `Modify, make derivative works of, disassemble, decrypt, reverse
    compile, or reverse engineer any part of the service.`,
    "restxt4": `Modify, make derivative works of, disassemble, decrypt, reverse
    compile, or reverse engineer any part of the service.`,

    // Suggest
    "suggest": "Your Suggestions",
    "sugtxt1": `Any feedback, comments, ideas, improvements, or
    suggestions (collectively, "Suggestions") provided by
    you to us with respect to the service shall remain the
    sole and exclusive property of us. We shall be free to
    use, copy, modify, publish, or redistribute the
    Suggestions for any purpose and in any way without any
    credit or any compensation to you.`,

    // Consent
    "consent": "Your Consent",
    "contxt1": `We've updated our Terms & Conditions to provide you with
    complete transparency into what is being set when you
    visit our site and how it's being used. By using our
    service, or registering an account, you hereby consent to our Terms & Conditions.`,

    // Modifications to Our Service
    "mod": "Modifications to Our Service",
    "modtxt1": `We reserve the right to modify, suspend, or discontinue, temporarily or
    permanently, the service or any service to which it connects, with or
    without notice and without liability to you.`,

    // Updates to Our Service
    "update": "Updates to Our Service",
    "updatetxt": `We may from time to time provide enhancements or
    improvements to the features/ functionality of the
    service, which may include patches, bug fixes, updates,
    upgrades, and other modifications ("Updates"). Updates
    may modify or delete certain features and/or
    functionalities of the service. You agree that we have
    no obligation to (i) provide any Updates, or (ii)
    continue to provide or enable any particular features
    and/or functionalities of the service to you. You
    further agree that all Updates will be (i) deemed to
    constitute an integral part of the service, and (ii)
    subject to the terms and conditions of this Agreement.`,

    // Third-Party Services
    "third": "Third-Party Services",
    "thirdtxt1": `We may display, include, or make available third-party
    content (including data, information, applications, and
    other products and services) or provide links to
    third-party websites or services ("Third-Party
    Services"). You acknowledge and agree that we shall not
    be responsible for any Third-Party Services, including
    their accuracy, completeness, timeliness, validity,
    copyright compliance, legality, decency, quality, or any
    other aspect thereof. We do not assume and shall not
    have any liability or responsibility to you or any other
    person or entity for any Third-Party Services.
    Third-party services and links thereto are provided
    solely as a convenience to you and you access and use
    them entirely at your own risk and subject to such third
    parties’ terms and conditions.`,

    // Links to Other Websites
    "link": "Links to Other Websites",
    "linktxt": `Our service may contain links to other websites that are
    not operated by Us. If You click on a third-party link,
    You will be directed to that third-party's site. We
    strongly advise You to review the Terms & Conditions of
    every site You visit. We have no control over and assume
    no responsibility for the content, Terms & Conditions,
    or practices of any third-party sites or services.`,

    // Cookies
    "cookies": "Cookies",
    "cookistxt": `We use "Cookies" to identify the areas of our website
    that you have visited. A Cookie is a small piece of data
    stored on your computer or mobile device by your web
    browser. We use Cookies to enhance the performance and
    functionality of our service but are non-essential to
    their use. However, without these cookies, certain
    functionality like videos may become unavailable or you
    would be required to enter your login details every time
    you visit our platform as we would not be able to
    remember that you had logged in previously. Most web
    browsers can be set to disable the use of Cookies.
    However, if you disable Cookies, you may not be able to
    access functionality on our website correctly or at all.
    We never place Personally Identifiable Information in
    Cookies.`,

    // Changes To Our Terms & Conditions
    "change": "Changes To Our Terms & Conditions",
    "changetxt": `You acknowledge and agree that we may stop (permanently or temporarily)
    providing the Service (or any features within the Service) to you or to
    users generally at our sole discretion, without prior notice to you. You
    may stop using the Service at any time. You do not need to specifically
    inform us when you stop using the Service. You acknowledge and agree
    that if we disable access to your account, you may be prevented from
    accessing the Service, your account details, or any files or other
    materials which is contained in your account. If we decide to change our
    Terms & Conditions, we will post those changes on this page, and/or
    update the Terms & Conditions modification date below.`,

    // Term and Termination
    "termter": "Term and Termination",
    "termtertxt": `This Agreement shall remain in effect until terminated
    by you or us. We may, in its sole discretion, at any
    time and for any or no reason, suspend or terminate this
    Agreement with or without prior notice. This Agreement
    will terminate immediately, without prior notice from
    us, in the event that you fail to comply with any
    provision of this Agreement. You may also terminate this
    Agreement by deleting the service and all copies thereof
    from your computer. Upon termination of this Agreement,
    you shall cease all use of the service and delete all
    copies of the service from your computer. Termination of
    this Agreement will not limit any of our rights or
    remedies at law or in equity in case of breach by you
    (during the term of this Agreement) of any of your
    obligations under the present Agreement.` ,

    "termtertxt2": `If you are a copyright owner or such owner's agent and
    believe any material from us constitutes an infringement
    on your copyright, please contact us setting forth the
    following information: (a) a physical or electronic
    signature of the copyright owner or a person authorized
    to act on his behalf; (b) identification of the material
    that is claimed to be infringing; (c) your contact
    information, including your address, telephone number,
    and an email; (d) a statement by you that you have a
    good faith belief that use of the material is not
    authorized by the copyright owners; and (e) the
    statement that the information in the notification is
    accurate, and, under penalty of perjury you are
    authorized to act on behalf of the owner.`,

    // Indemnification
    "indem": "Indemnification",
    "indemtxt": `You agree to indemnify and hold us and our parents, 
    subsidiaries, affiliates, officers, employees, agents, partners, 
    and licensors (if any) harmless from any claim or demand, including 
    reasonable attorneys' fees, due to or arising out of your: 
    (a) use of the service; (b) violation of this Agreement or any law 
    or regulation; or (c) violation of any right of a third party.`,

    // No Warranties
    "nowan": "No Warranties",
    "nowantxt": `The service is provided to you "AS IS" and "AS
    AVAILABLE" and with all faults and defects without
    warranty of any kind. To the maximum extent permitted
    under applicable law, we, on our own behalf and on
    behalf of our affiliates and our respective licensors
    and service providers, expressly disclaims all
    warranties, whether express, implied, statutory, or
    otherwise, with respect to the service, including all
    implied warranties of merchantability, fitness for a
    particular purpose, title and non-infringement, and
    warranties that may arise out of course of dealing,
    course of performance, usage or trade practice. Without
    limitation to the foregoing, we provide no warranty or
    undertaking, and makes no representation of any kind
    that the service will meet your requirements, achieve
    any intended results, be compatible or work with any
    other software, websites, systems, or services, operate
    without interruption, meet any performance or
    reliability standards or be error-free or that any
    errors or defects can or will be corrected.`,
    "nowantxt2": `Without limiting the foregoing, neither we nor any
    provider makes any representation or warranty of any
    kind, express or implied: (i) as to the operation or
    availability of the service, or the information,
    content, and materials or products included thereon;
    (ii) that the service will be uninterrupted or
    error-free; (iii) as to the accuracy, reliability, or
    currency of any information or content provided through
    the service; or (iv) that the service, its servers, the
    content, or e-mails sent from or on behalf of us are
    free of viruses, scripts, trojan horses, worms, malware,
    timebombs or other harmful components. Some
    jurisdictions do not allow the exclusion of or
    limitations on implied warranties or the limitations on
    the applicable statutory rights of a consumer, so some
    or all of the above exclusions and limitations may not
    apply to you.`,

    // Limitation of Liability
    "limit": "Limitation of Liability",
    "limittxt": `Notwithstanding any damages that you might incur, the entire liability
    of us and any of our suppliers under any provision of this Agreement and
    your exclusive remedy for all of the foregoing shall be limited to the
    amount actually paid by you for the service. To the maximum extent
    permitted by applicable law, in no event shall we or our suppliers be
    liable for any special, incidental, indirect, or consequential damages
    whatsoever (including, but not limited to, damages for loss of profits,
    for loss of data or other information, for business interruption, for
    personal injury, for loss of privacy arising out of or in any way
    related to the use of or inability to use the service, third-party
    software and/or third-party hardware used with the service, or otherwise
    in connection with any provision of this Agreement), even if we or any
    supplier has been advised of the possibility of such damages and even if
    the remedy fails of its essential purpose. Some states/jurisdictions do
    not allow the exclusion or limitation of incidental or consequential
    damages, so the above limitation or exclusion may not apply to you.`,

    // Severability
    "sever": "Severability",
    "severtxt": `If any provision of this Agreement is held to be unenforceable or
    invalid, such provision will be changed and interpreted to accomplish
    the objectives of such provision to the greatest extent possible under
    applicable law and the remaining provisions will continue in full force
    and effect.`,
    "severtxt2": `This Agreement, together with the Privacy Policy and any other legal
    notices published by us on the Services, shall constitute the entire
    agreement between you and us concerning the Services. If any provision
    of this Agreement is deemed invalid by a court of competent
    jurisdiction, the invalidity of such provision shall not affect the
    validity of the remaining provisions of this Agreement, which shall
    remain in full force and effect. No waiver of any term of this Agreement
    shall be deemed a further or continuing waiver of such term or any other
    term, and our failure to assert any right or provision under this
    Agreement shall not constitute a waiver of such right or provision. YOU
    AND US AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE
    SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION
    ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.`,

    // Waiver
    "waiver": "Waiver",
    "waivertxt": `Except as provided herein, the failure to exercise a
    right or to require the performance of an obligation
    under this Agreement shall not effect a party's ability
    to exercise such right or require such performance at
    any time thereafter nor shall be the waiver of a breach
    constitute waiver of any subsequent breach.`,
    "waivertxt2": `No failure to exercise, and no delay in exercising, on the part of
    either party, any right or any power under this Agreement shall operate
    as a waiver of that right or power. Nor shall any single or partial
    exercise of any right or power under this Agreement preclude further
    exercise of that or any other right granted herein. In the event of a
    conflict between this Agreement and any applicable purchase or other
    terms, the terms of this Agreement shall govern.`,

    // Amendments to this Agreement
    "amend": "Amendments to this Agreement",
    "amendtxt": `We reserve the right, at its sole discretion, to modify
    or replace this Agreement at any time. If a revision is
    material we will provide at least 30 days' notice prior
    to any new terms taking effect. What constitutes a
    material change will be determined at our sole
    discretion. By continuing to access or use our service
    after any revisions become effective, you agree to be
    bound by the revised terms. If you do not agree to the
    new terms, you are no longer authorized to use our
    service.`,

    // Entire Agreement
    "entire": "Entire Agreement",
    "entiretxt": `The Agreement constitutes the entire agreement between you and us
    regarding your use of the service and supersedes all prior and
    contemporaneous written or oral agreements between you and us. You may
    be subject to additional terms and conditions that apply when you use or
    purchase other services from us, which we will provide to you at the
    time of such use or purchase.`,

    // Updates to Our Terms
    "uptoteam": "Updates to Our Terms",
    "uptoteamtxt": `We may change our Service and policies, and we may need to make changes
    to these Terms so that they accurately reflect our Service and policies.
    Unless otherwise required by law, we will notify you (for example,
    through our Service) before we make change to these Terms and give you
    an opportunity to review them before they go into effect. Then, if you
    continue to use the Service, you will be bound by the updated Terms. If
    you do not want to agree to these or any updated Terms, you can delete
    your account.`,

    // Intellectual Property
    "intell": "Intellectual Property",
    "intelltxt": `Our platform and its entire contents, features, and functionality
    (including but not limited to all information, software, text, displays,
    images, video and audio, and the design, selection, and arrangement
    thereof), are owned by us, its licensors or other providers of such
    material and are protected by Thailand and international copyright,
    trademark, patent, trade secret and other intellectual property or
    proprietary rights laws. The material may not be copied, modified,
    reproduced, downloaded, or distributed in any way, in whole or in part,
    without the express prior written permission of us, unless and except as
    is expressly provided in these Terms & Conditions. Any unauthorized use
    of the material is prohibited.`,

    // Agreement to Arbitrate
    "agreement": "Agreement to Arbitrate",
    "agreementtxt": `This section applies to any dispute EXCEPT IT DOESN'T
    INCLUDE A DISPUTE RELATING TO CLAIMS FOR INJUNCTIVE OR
    EQUITABLE RELIEF REGARDING THE ENFORCEMENT OR VALIDITY
    OF YOUR OR’s INTELLECTUAL PROPERTY RIGHTS. The term
    “dispute” means any dispute, action, or other
    controversy between you and us concerning the Services
    or this agreement, whether in contract, warranty, tort,
    statute, regulation, ordinance, or any other legal or
    equitable basis. “Dispute” will be given the broadest
    possible meaning allowable under law.`,

    // Notice of Dispute
    "notice": "Notice of Dispute",
    "noticetxt": `In the event of a dispute, you or us must give the other
    a Notice of Dispute, which is a written statement that
    sets forth the name, address, and contact information of
    the party giving it, the facts giving rise to the
    dispute, and the relief requested. You must send any
    Notice of Dispute via email to: . We will send any
    Notice of Dispute to you by mail to your address if we
    have it, or otherwise to your email address. You and us
    will attempt to resolve any dispute through informal
    negotiation within sixty (60) days from the date the
    Notice of Dispute is sent. After sixty (60) days, you or
    us may commence arbitration.`,

    // Binding Arbitration
    "binding": "Binding Arbitration",
    "bindingtxt": `If you and us don’t resolve any dispute by informal
    negotiation, any other effort to resolve the dispute
    will be conducted exclusively by binding arbitration as
    described in this section. You are giving up the right
    to litigate (or participate in as a party or class
    member) all disputes in court before a judge or jury.
    The dispute shall be settled by binding arbitration in
    accordance with the commercial arbitration rules of the
    American Arbitration Association. Either party may seek
    any interim or preliminary injunctive relief from any
    court of competent jurisdiction, as necessary to protect
    the party's rights or property pending the completion of
    arbitration. Any and all legal, accounting, and other
    costs, fees, and expenses incurred by the prevailing
    party shall be borne by the non-prevailing party.`,

    // Submissions and Privacy
    "submiss": "Submissions and Privacy",
    "submisstxt": `In the event that you submit or post any ideas, creative suggestions,
    designs, photographs, information, advertisements, data, or proposals,
    including ideas for new or improved products, services, features,
    technologies, or promotions, you expressly agree that such submissions
    will automatically be treated as non-confidential and non-proprietary
    and will become the sole property of us without any compensation or
    credit to you whatsoever. We and our affiliates shall have no
    obligations concerning such submissions or posts and may use the ideas
    contained in such submissions or posts for any purposes in any medium in
    perpetuity, including, but not limited to, developing, manufacturing,
    and marketing products and services using such ideas.`,

    // Typographical Errors
    "typo": "Typographical Errors",
    "typotxt": `In the event a product and/or service is listed at an incorrect price or
    with incorrect information due to typographical error, we shall have the
    right to refuse or cancel any orders placed for the product and/ or
    service listed at the incorrect price. We shall have the right to refuse
    or cancel any such order whether or not the order has been confirmed and
    your credit card charged. If your credit card has already been charged
    for the purchase and your order is canceled, we shall immediately issue
    a credit to your credit card account or other payment account in the
    amount of the charge.`,

    // Miscellaneous
    "miscel": "Miscellaneous",
    "misceltxt": `If for any reason a court of competent jurisdiction finds any provision
    or portion of these Terms & Conditions to be unenforceable, the
    remainder of these Terms & Conditions will continue in full force and
    effect. Any waiver of any provision of these Terms & Conditions will be
    effective only if in writing and signed by an authorized representative
    of us. We will be entitled to injunctive or other equitable relief
    (without the obligations of posting any bond or surety) in the event of
    any breach or anticipatory breach by you. We operate and control our
    Service from our offices in Thailand. The Service is not intended for
    distribution to or use by any person or entity in any jurisdiction or
    country where such distribution or use would be contrary to law or
    regulation. Accordingly, those persons who choose to access our Service
    from other locations do so on their own initiative and are solely
    responsible for compliance with local laws, if and to the extent local
    laws are applicable. These Terms & Conditions (which include and
    incorporate our Privacy Policy) contains the entire understanding and
    supersedes all prior understandings, between you and us concerning its
    subject matter, and cannot be changed or modified by you. The section
    headings used in this Agreement are for convenience only and will not be
    given any legal import.`,

    // Disclaimer
    "disclaimer": "Disclaimer",
    "disclaimertxt": `We are not responsible for any content, code, or any other imprecision.
    We do not provide warranties or guarantees. In no event shall we be
    liable for any special, direct, indirect, consequential, or incidental
    damages or any damages whatsoever, whether in an action of contract,
    negligence, or other tort, arising out of or in connection with the use
    of the Service or the contents of the Service. We reserve the right to
    make additions, deletions, or modifications to the contents of the
    Service at any time without prior notice.`,

    "disclaimertxt2": `Our Service and its contents are provided "as is" and
    "as available" without any warranty or representations
    of any kind, whether express or implied. We are a
    distributor and not a publisher of the content supplied
    by third parties; as such, the developer exercises no
    editorial control over such content and makes no
    warranty or representation as to the accuracy,
    reliability, or currency of any information, content,
    service, or merchandise provided through or accessible
    via our Service. Without limiting the foregoing, We
    specifically disclaim all warranties and representations
    in any content transmitted on or in connection with our
    Service or on sites that may appear as links on our
    Service, or in the products provided as a part of, or
    otherwise in connection with, our Service, including
    without limitation any warranties of merchantability,
    fitness for a particular purpose or non-infringement of
    third party rights. No oral advice or written
    information given by us or any of its affiliates,
    employees, officers, directors, agents, or the like will
    create a warranty. Price and availability information is
    subject to change without notice. Without limiting the
    foregoing, we do not warrant that our Service will be
    uninterrupted, uncorrupted, timely, or error-free.`,

    // Contact Us
    "contact": "Contact Us",
    "contacttxt": "Don't hesitate to contact us if you have any questions.",
    "contacttxt2": "Via Email: capcap241023@gmail.com"
  },

  "privacypolicypage": {
    "title": "Privacy Policy",
    "privacytxt": `Thai.CheckLinks ("we," "our," or "us") is committed to
    protecting your privacy. This Privacy Policy explains how
    your personal information is collected, used, and
    disclosed by Thai.CheckLinks. This Privacy Policy applies to
    our website, www.Thai.CheckLinks.com, and its associated
    subdomains (collectively, our "Service"). By accessing or
    using our Service, you signify that you have read,
    understood, and agree to our collection, storage, use, and
    disclosure of your personal information as described in
    this Privacy Policy and our Terms of Service.`,

    // Definitions and key terms
    "definition": "Definitions and key terms",
    "deftxt": `To help explain things as clearly as possible in this Privacy Policy,
    every time any of these terms are referenced, are strictly defined as:`,

    // Topic1
    "topic1": "What Information Do We Collect?",
    "topic1txt": `We collect information from you when you visit our service, register, subscribe to our newsletter, respond to a survey, or
    fill out a form.`,
    "topic1txt2": "Name / Username",
    "topic1txt3": "Phone Numbers",
    "topic1txt4": "Email Addresse",
    "topic1txt5": "Password",

    // Topic2
    "topic2": "How Do We Use The Information We Collect?",
    "topic2txt": `Any of the information we collect from you may be used in one of the
    following ways:`,
    "topic2txt2": `To personalize your experience (your information helps us to better
      respond to your individual needs)`,
    "topic2txt3": `To improve our service (we continually strive to improve our service
      offerings based on the information and feedback we receive from you)`,
    "topic2txt4": `To improve customer service (your information helps us to more
      effectively respond to your customer service requests and support
      needs)`,
    // Topic3
    "topic3": "Could my information be transferred to other countries?",
    "topic3txt": `We are incorporated in Thailand. Information collected via our website,
    through direct interactions with you, or from the use of our help
    services may be transferred from time to time to our offices or
    personnel, or to third parties, located throughout the world, and may be
    viewed and hosted anywhere in the world, including countries that may
    not have laws of general applicability regulating the use and transfer
    of such data. To the fullest extent allowed by applicable law, by using
    any of the above, you voluntarily consent to the trans-border transfer
    and hosting of such information.`,

    // Topic4
    "topic4": "Is the information collected through our service secure?",
    "topic4txt": `We take precautions to protect the security of your information. We have
    physical, electronic, and managerial procedures to help safeguard,
    prevent unauthorized access, maintain data security, and correctly use
    your information. However, neither people nor security systems are
    foolproof, including encryption systems. In addition, people can commit
    intentional crimes, make mistakes, or fail to follow policies.
    Therefore, while we use reasonable efforts to protect your personal
    information, we cannot guarantee its absolute security. If applicable
    law imposes any non-disclaimable duty to protect your personal
    information, you agree that intentional misconduct will be the standard
    used to measure our compliance with that duty.`,

    // Topic5
    "topic5": "Can I update or correct my information?",
    "topic5txt": "Of course! You can be able to update your data via the profile page.",

    // Topic 6
    "topic6": "How Long Do We Keep Your Information?",
    "topic6txt": `We keep your information only so long as we need it to
    provide service to you and fulfill the purposes described
    in this policy. This is also the case for anyone that we
    share your information with and who carries out services
    on our behalf. When we no longer need to use your
    information and there is no need for us to keep it to
    comply with our legal or regulatory obligations, we'll
    either remove it from our systems or depersonalize it so
    that we can't identify you.`,

    // Topic 7
    "topic7": "Governing Law",
    "topic7txt": `The laws of Thailand, excluding its conflicts of law rules, shall govern
    this Agreement and your use of our service. Your use of our service may
    also be subject to other local, state, national, or international laws.`,

    // Topic 8
    "topic8": "Your Consent",
    "topic8txt": `By using our service, registering an account, you consent to this
    Privacy Policy.`,

    // Topic 9 Cookies
    "topic9": "Cookies",
    "topic9txt": `We use "Cookies" to identify the areas of our website that
    you have visited. A Cookie is a small piece of data stored
    on your computer or mobile device by your web browser. We
    use Cookies to personalize the Content that you see on our
    website. Most web browsers can be set to disable the use
    of Cookies. However, if you disable Cookies, you may not
    be able to access functionality on our website correctly
    or at all. We never place Personally Identifiable
    Information in Cookies.`,

    // Topic 10
    "topic10": "Kids’ Privacy",
    "topic10txt": `We do not address anyone under the age of 13. We do not knowingly
    collect personally identifiable information from anyone under the age of
    13. If You are a parent or guardian and You are aware that Your child
    has provided Us with Personal Data, please contact us. If We become
    aware that We have collected Personal Data from anyone under the age of
    13 without verification of parental consent, We take steps to remove
    that information from our servers.`,

    // Topic 11
    "topic11": "Changes To Our Privacy Policy",
    "topic11txt": `If we decide to change our privacy policy, we will post those changes on
    this page, and/or update the Privacy Policy modification date below.`,

    // Topic 12
    "topic12": "Tracking Technologies",
    "topic12txt": "Cookies",
    "topic12txt2": `We use Cookies to enhance the performance and functionality of our
    service but are non-essential to their use. However, without these
    cookies, certain functionality like videos may become unavailable or you
    would be required to enter your login details every time you visit our
    service as we would not be able to remember that you had logged in
    previously.`,
    "topic12txt3": "Local Storage",
    "topic12txt4": `Local Storage sometimes known as DOM storage, provides web apps with
    methods and protocols for storing client-side data. Web storage supports
    persistent data storage, similar to cookies but with a greatly enhanced
    capacity and no information stored in the HTTP request header.`,
    "topic12txt5": "Sessions",
    "topic12txt6": `uses "Sessions" to identify the areas of our website that
    you have visited. A Session is a small piece of data
    stored on your computer or mobile device by your web
    browser.`,

    // Topic 13
    "topic13": "Information about the Personal Data Protection Act (PDPA) of Thailand",
    "topic13txt": `We may be collecting and using information from you if you are in
    Thailand, and in this section of our Privacy Policy, we are going to
    explain exactly how and why this data is collected, and how we maintain
    this data under protection from being replicated or used in the wrong
    way.`,

    // Topic 14
    "topic14": "What is PDPA?",
    "topic14txt": `PDPA is a comprehensive privacy and data protection law in
    Thailand that regulates how individuals' data is protected
    by companies and enhances the control that individuals
    have over their personal data.`,

    // Topic 15
    "topic15": "What is personal data?",
    "topic15txt": `Personal data, as defined by PDPA, refers to any information relating to
    an identifiable individual. PDPA covers a broad spectrum of information
    that could be used, either alone or in combination with other pieces of
    information, to identify a person. Examples include but are not limited
    to, name, contact details, financial information, biometric data, IP
    addresses, and more.`,
    "topic15txt2": `The Data Protection Principles outlined in PDPA include requirements
    such as:`,
    "topic15txt3": `Personal data collected must be processed in a fair, legal, and
    transparent way and should only be used in a way that a person would
    reasonably expect.`,
    "topic15txt4": `Personal data should only be collected to fulfill a specific purpose,
    and it should only be used for that purpose. Organizations must
    specify why they need the personal data when they collect it.`,
    "topic15txt5": `Personal data should be held no longer than necessary to fulfill its
    purpose.`,
    "topic15txt6": `Individuals covered by PDPA have the right to access their own personal
    data. They can also request a copy of their data, and that their data be
    updated, deleted, restricted, or transferred to another organization.`,

    // Topic 16
    "topic16": "Why is PDPA important?",
    "topic16txt": `PDPA introduces new requirements regarding how companies
    should protect individuals’ personal data that they
    collect and process. It emphasizes compliance through
    increased enforcement and imposes penalties for breaches.
    Beyond these legal requirements, we believe that
    respecting your data privacy is crucial. At Thai.CheckLinks, we have robust security and privacy practices in
    place that go beyond the PDPA regulations.`,

    // Topic 17
    "topic17": `Individual Data Subject's Rights - Data Access, Portability, and Deletion`,
    "topic17txt": `We are committed to helping our customers meet the data subject rights
    requirements of PDPA. Thai.CheckLinks.com processes or stores all personal
    data in fully vetted, PDPA-compliant vendors. We retain all conversation
    and personal data for up to 2024, unless your account is deleted. In
    such cases, we dispose of all data in accordance with our Terms of
    Service and Privacy Policy, but we will not hold it for longer than
    2025.`,
    "topic17txt2": `We acknowledge the importance of providing individuals
    with the ability to access, update, retrieve, and remove
    personal data. We have designed our systems to be
    self-service from the start, ensuring that you have access
    to your data and your customer's data. Our customer
    support team is here to assist you with any questions you
    may have about working with the PDPA.`,
  },

  "homepage": {
    "title": "Start Checking Website Links For Your Safety",
    "caption": "Enter your link in the verification box to check your website and stage percentage of scammers against the criminal history database.",
    "text": "Search URL link or category",
    "verify": "Verify",
    "rank": "Ranking fraudulent links",
    "detail": "Details",
    "category": "Category",
    "reportnum": "Reports Number",
    "more": "More details",
    "searchbutt": "Search",
    "reportbutt": "Report",
    "filter": "Filter",
    "alldefault": "All Defaults",
    "date": "Date/Time",
    "old": "Oldest Date",
    "new": "Latest Date",
    "report": "Report Number",
    "high": "Highest Report",
    "low": "Lowest Report",
    "gambling": "Gambling",
    "scam": "Scam",
    "fake": "Fake",
    "others": "Others",
    "seemore": "See More",
    "seeall": "See All",
    "seeless": "See Less",
    "placeholder": "Enter link eg. https://www.example.com ...",
    "sort": "Sorting Filter"
  },

  "detailpage": {
    "title": "Crime Wesite Details",
    "category": "Category",
    "gambling": "Gambling",
    "scam": "Scam",
    "fake": "Fake",
    "others": "Others",
    "gamblingr": "Gambling Report",
    "scamr": "Scam Report",
    "faker": "Fake Report",
    "othersr": "Others Report",
    "searchtext": "Search Word",
    "searchbutt": "Search",
    "detail": "Details",
    "bank": "Bank Account",
    "more": "See More",
    "seemore": "See More",
    "seeall": "See All",
    "seeless": "See Less",
    "user": "User",
    "phone": "Phone Number"
  },

  "report": {
    "title": "Start reporting suspicious website links",
    "caption": "Sign in or sign up before reporting information to ensure accuracy.",
    "signin": "Sign In",
    "signup": "Sign Up",
    "caption2": "Reporting unlawful links here can help investigators find criminal websites",
    "placeholder": "Enter link eg. https://www.example.com ...",
    "searchbutt": "Confirm",
    "Category": "Categories of suspicious links*",
    "typefield": "Categories",
    "moredetails": "How does this website risk*",
    "details": "Details (At Least 10 characters and not over 500 characters)",
    "bankacc": "Criminals bank and Phone number information (Optional)",
    "bankacctxt": "Bank Account:",
    "banktext": "Bank Account Holder Name (Select 1 account if there are many)",
    "bankfield1": "Bank Account",
    "banknum": "Bank Account Number",
    "phonenumtxt": "Phone Number:",
    "phonenum": "Phone Number",
    "reportbutt": "Report",
    "gambling": "Gambling",
    "scam": "Scam",
    "fake": "Fake",
    "others": "Others",
    "bank": "Bank",
    "scb": "Siam Commercial Bank",
    "kbtg": "Kasikorn Bank",
    "ktb": "Krungthai Bank",
    "ttb": "TMBThanachart Bank",
    "boa": "Bank of Ayudhya",
    "lhb": "Land and Houses Bank",
    "gsb": "Government Savings Bank",
    "bankothers": "Others",
    "urlError": "Please provide the URL",
    "urlError2": "Please provide the correct URL's format",
    "urlError3": "URL contains invalid characters",
    "webCatError": "Please select your website category",
    "moredetailError": "Please provide more details about this website",
    "moredetailError2": "Please ensure your input contains between 10 and 500 characters.",
    "moredetailError3": "Please do not use the redundancy word over 3 times",
  },

  "reportsuccess": {
    "title": "Successfully reported suspicious website links",
    "sub-title": "Thank you for reporting suspicious links here.",
    "sub-title2": "We will continue to use criminal web investigations to help the public.",
    "successmess": "Successful report"
  },

  "profilepage": {
    "title": "My Profile",
    "caption": "Sign in or sign up before viewing your profile information.",
    "username": "Username",
    "email": "Email",
    "phonenum": "Phone number (Optional)",
    "password": "Password",
  },

  "verificationpage": {
    "title": "Start Checking Website Links For Your Safety",
    "caption": "Enter your link in the verification box to check your website and stage percentage of scammers against the criminal history database.",
    "url-detection-title": "URL Detection",
    "No Result": "No Result",
    "cannotclassify": `Insufficient Information`,
    "report": "Report",

    "overall-title": "Overview Of The Risks Of Website",
    "overall-subtitle": "The Percentage Of Risk Of Being An suspicious Website Is Based On All Citeria",
    "risk-value": "Risk value",
    "sum-percentage": "Total percentage",
    "low-score": "Low Risk",
    "quite-low-score": "Quite Low Risk",
    "quite-high-score": "Quite High Risk",
    "high-score": "High Risk",
    'risk-measurement-citeria': "Risk Measurement Criteria",
    "found-thai-scam-link": "Found In History Website Reported in Thai.CheckLinks",
    "found-ai": "Discover In AI Audit Risk Percentage",
    "url-measure": "URL Risks Measured By URL Detection",
    "found-other-database": "Found On The Other Website Checker",
    "seemore": "See More",
    "click-here": "Click here for addtional reports",

    "analysis-title": "AI Analyzes Risk Percent",
    "analysis-subtitle": "Highest Percentage Ever Examined",
    "see-overview": "SEE THE OVERVIEW",
    'update': 'current update',
    'analysis-most': "Analyzed as a",

    "report-title": "Verify The Database",
    "report-subtitle": "Verify Against The User Reporting Database In Thai.ScamLinks",
    "report-title-result": "Verification Result",
    "risk-title-count": "Risk rate based on number of reports",

    "low-risk-count": "Low risk with 0-5 reports",
    "moderate-risk-count": "Moderate risk with 6-10 reports",
    "quite-high-risk-count": "Quite high risk with 11-15 reports",
    "serious-risk-count": "Serious risk with 16+ reports",

    "low-count": "Low Risk",
    "quite-low-count": "Quite Low Risk",
    "quite-high-count": "Quite High Risk",
    "high-count": "Serious Risk",

    "gambling-label": "Gambing",
    "scam-label": "Scam",
    "fake-label": "Fake",
    "other-label": "Other",
    "gambling": "gambling",
    "scam": "scam",
    "fake": "fake",
    "other": "other",

    'report-found': 'FOUND IN DATABASE',
    'report-not-found': 'NOT FOUND IN DATABASE',
    'report-not-found2': 'FOUND BEING TYPE OTHER IN THE DATABASE',

    'report-most': "Most reported as",
    'report-unit': "People",

    "report-label-bar-plot": "Number of each type of reporting",

    "measure-title": "Verify From URL Detection",
    "measure-subtitle": "Check For Risks From URL Information",
    "measure-risk-title": "Risk Score",

    "API-title": "Compare API With Other Cheat Checking Websites",
    "API-subtitle": "Check The Website Againt A Database Of Other Verified Websites",
    "API-website-col": "Cheating Web Checking Websites",
    "API-inspection-result-col": "Inspection Results",
    "FOUND": "FOUND",
    "NOT FOUND": "NOT FOUND",
  },

  "moredetailpage": {
    "title": "Read More Website Details Here",
    "risk-score": "Risk Score:",
    "measurement": "Trust Score Measurement Criteria",
    "websiteinsight-title": "Website Insights",
    "API-title": "Compare API With Other Cheat Checking Websites",
    "API-website-col": "Cheating Web Checking Websites",
    "API-inspection-result-col": "Inspection Results",
    "FOUND": "FOUND",
    "NOT FOUND": "NOT FOUND",
    "No Result": "No Result",
    'positive': 'Positive',
    'negative': 'Negative'
  },

  "errormessage": {
    "errmessuserexist": "User with this username already exists",
    "errmessemailexist": "User with this email already exists",
    "errmessphoneexist": "User with this phone number already exists",
    "errmesspassword": "You can not change your password with your old password",
    "editnoinfo": "Require information for an update",
    "editerrinfo": "Something Wrong with your information",
    "editsuccess": "User information was edited successfully",
    "usersuccess": "User information was created successfully",
    "errsigninusername": "The provided username does not exist. Please sign up if you don't have an account.",
    "errsigninpassword": "Invalid password",
    "errnoinfosignin": "Please provide your username or password",
    "errsigninsystem": "Please try to complete your login or password again.",
    "signinsuccess": "Authentication successful",
    "reporterrwebsiteinact": "This website may no longer be available. Therefore, the overall risk and AI Classify value cannot be displayed.",
    "reportsuccess": "Report information was created successfully",
    "errurl1": "This website is already inactive but user still can report this website",
    "errurl2": "Please check the machine learning connection but the user still can report this website",
    "caution": "Caution",
  }
}